name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: powershell
          container_name: publicscripts
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: '--pattern *.ps1'
          sync: false